# Create EC2 instances

- name: Create EC2 security groups
  local_action:
    module: ec2_group
    vpc_id: "{{amazon.vpc.id}}"
    name: "{{amazon.vpc.id}}_{{amazon.client}}_{{amazon.env}}_{{item.key}}_sg"
    description: "{{amazon.vpc.id}}_{{amazon.client}}_{{amazon.env}}_{{item.key}} security group rules"
  with_dict: amazon.instances
  tags: security

- name: Apply EC2 security group rules
  local_action:
    module: ec2_group
    vpc_id: "{{amazon.vpc.id}}"
    name: "{{amazon.vpc.id}}_{{amazon.client}}_{{amazon.env}}_{{item.key}}_sg"
    description: "{{amazon.vpc.id}}_{{amazon.client}}_{{amazon.env}}_{{item.key}} security group rules"
    rules: "{{item.value.security_group.rules}}"
  with_dict: amazon.instances
  tags: security

- name: Create EC2 instances
  local_action:
    module: ec2
    assign_public_ip: yes
    vpc_subnet_id: "{{amazon.vpc.subnet}}"
    key_name: "{{keypair}}"
    instance_type: "{{item.value.type}}"
    group: "{{amazon.vpc.id}}_{{amazon.client}}_{{amazon.env}}_{{item.key}}_sg"
    instance_tags:
      Client: "{{amazon.client}}"
      Environment: "{{amazon.env}}"
      ClientEnvironment: "{{amazon.client}}.{{amazon.env}}"
      Name: "{{amazon.client}}.{{amazon.env}}.{{item.key}}"
      Role: "{{item.value.role}}"
      ClusterRole: "{{item.key}}"
      CompleteDesignation: "{{amazon.client}}_{{amazon.env}}_{{item.key}}"
    image: "{{item.value.ami}}"
    wait: yes
    exact_count: "{{item.value.count}}"
    count_tag :
       Client: "{{amazon.client}}"
       ClusterRole: "{{item.key}}"
       Environment: "{{amazon.env}}"
  register: "ec2result"
  with_dict: amazon.instances
