# playbook for Mesos slave

- hosts: "{{lookup('env','CLIENT')}}_{{lookup('env','ENV')}}_mesos_slave"
  user: admin
  sudo: yes

  roles:
    - all
    - java
    - docker
    - mesos
    - mesos-slave
