# playbook for destroying infrastructure

- hosts: "{{lookup('env','CLIENT')}}.{{lookup('env','STAGE')}}.elasticsearch.autoscalinggroup"
  gather_facts: true
  connection: local

  tasks:

    - name: Delete EC2 Auto Scaling Group
      local_action:
        module: ec2_asg
        name: "{{env.client}}.{{env.stage}}.elasticsearch.autoscalinggroup"
        state: absent

    - name: Delete EC2 Launch configuration
      local_action:
        module: ec2_lc
        name: "{{env.client}}.{{env.stage}}.elasticsearch.launchconfiguration"
        state: absent

    - name: Delete EC2 ELB
      local_action:
         module: ec2_elb_lb
         name: "{{env.client}}-{{env.stage}}-elasticsearch-elb"
         state: absent

    - name: Terminate all instances
      local_action:
        module: ec2
        state: absent
        instance_ids: "{{ ec2_id }}"

    - name: Delete AMI
      local_action:
        module: ec2_ami
        image_id: "{{ ami.es_image }}"
        delete_snapshot: True
        state: absent
